services:
  - type: web
    name: campuswallet-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: CampusWallet <noreply@campuswallet.app>
      - key: FRONTEND_URL
        value: https://campus-wallet-pi.vercel.app
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
